spring.datasource:
  type: org.postgresql.ds.PGSimpleDataSource
  username: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/camunda

camunda.bpm.admin-user:
  id: demo
  password: demo

camunda:
  bpm:
    job-execution:
      lock-time-in-millis: 7200000

logging:
  level:
    org.camunda: debug
    org.springframework: debug
    org.hibernate: debug
    root: info
  file:
    path: D:/logs/


spring.mail:
  host: smtp.gmail.com
  port: 587
  username: a.koniushenko@crystals.ru
  password: DerPar0l
  properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


bot:
  name: CSI_Test_Camunda_Bot
  token: 5587291320:AAH52dWxMrkFKTlo4EjcjfHiMqlv6nsPB_g
  chatId: -500642946

typeOfData:
  all: 1,2,3,4,31
  prod: 31
  mrc: 1,2,3,4

